#     _    _ _ ____  _
#    / \  | | / ___|(_) __ _ _ __  ___
#   / _ \ | | \___ \| |/ _` | '_ \/ __|
#  / ___ \| | |___) | | (_| | | | \__ \
# /_/   \_\_|_|____/|_|\__, |_| |_|___/
#                      |___/
# (C) 2021 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German), ru (Russian), ja(Japanese)
language: "en"
